---
# tasks file for roles/nginx
- name: copy repo file
  become: yes
  copy:
    src: files/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  become: yes
  yum: 
    name: nginx
    state: present

- name: service nginx start
  become: yes
  service: 
    name: nginx 
    enabled: yes 
    state: started

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  become: yes
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes   

- name: copy conf file
  become: yes
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf
