---
# tasks file for roles/gunicorn
- name: install gunicorn
  become: yes
  pip:
    name: gunicorn
    state: present

- name: start gunicorn
  command: "/usr/local/bin/gunicorn -w 4 -b 127.0.0.1:8000 run:app -D"
