---
- hosts: deploy
  tasks:
    # task 1
    - name: Get updated files from git repository
      git:
        repo: "https://twm-devops:09350935Ab@github.com/twm-gh/mymoji-api.git"
        dest: /home/mymoji/mymoji-api
        version: develop
      become: yes

    - name: migrate database
      command: python3 /home/mymoji/mymoji-api/manage.py db migrate
      args:
        chdir: /home/mymoji/mymoji-api/
      become: yes
      
    - name: upgrade database
      command: python3 /home/mymoji/mymoji-api/manage.py db upgrade
      args:
        chdir: /home/mymoji/mymoji-api/
      become: yes

    # task 2
    - name: supervisorctl restart app
      shell: supervisorctl restart app
      become: yes
