---
- hosts: deploy
  tasks:
    # task 1
    - name: Get updated files from git repository
      git:
        repo: "https://twm-devops:09350935Ab@github.com/twm-gh/mymoji-api.git"
        dest: /home/ericsychang/mymoji-api
        version: develop
      become: yes

    - name: migrate database
      command: python manage.py db migrate
      args: /home/ericsychang/mymoji-api
      
    - name: upgrade database
      command: python manage.py db upgarde
      args: /home/ericsychang/mymoji-api

    # task 2
    - name: supervisorctl restart app
      shell: supervisorctl restart app
      become: yes
