---
- hosts: web
  gather_facts: no
  
  # roles:
  #   - { role: common, become: yes }
  tasks:
    - name: install package
      become: yes
      yum:
        name: "{{packages}}"
        state: present

      vars:
        packages:
        - '*'
        - git
        - python3
        - python3-devel
        - python3-pip
        - python-setuptools

    - name: install flask
      become: yes
      pip3:
        name: flask
        state: present
