---
- hosts: web
  gather_facts: no
  
  roles:
    - common

  #   - name: install package
  #     become: yes
  #     yum:
  #       name: "{{packages}}"
  #       state: present

  #     vars:
  #       packages:
  #       - '*'
  #       - git
  #       - python3
  #       - python3-devel
  #       - python3-pip
  #       - python-pip
  #       - python-setuptools

  #   - name: install flask
  #     become: yes
  #     pip:
  #       name: flask
  #       state: present
