---
- hosts: web
  gather_facts: no
  
  # roles:
  #   - { role: common, become: yes }
  tasks:
    - name: install package
      yum:
        name: "{{packages}}"
        state: present

      vars:
        packages:
        - python3
        - python3-devel
        - python3-pip
        - python-setuptools

    - name: install flask
      pip:
        name: flask
        state: present
