---
- hosts: gcp
  gather_facts: yes
  become: yes
  
  pre_tasks:
    # - name: Adding MYSQL_ENDPOINT
    #   lineinfile: 
    #     dest=/etc/environment 
    #     line="MYSQL_ENDPOINT=35.189.191.8:3306"
    #     state=present
      
    # - name: Adding BUCKET_NAME
    #   lineinfile: 
    #     dest=/etc/environment
    #     line="BUCKET_NAME=dev_public_resource"  
    #     state=present

    # - name: Source environment file
    #   shell: . /etc/environment

    - name: common
      include_role:
        name: common

    - name: creates mymoji directory
      file:
        path: /home/mymoji/mymoji-api
        state: directory

    - name: Get files from git repository
      git:
          repo: "https://twm-devops:09350935Ab@github.com/twm-gh/mymoji-api.git"
          dest: /home/mymoji/mymoji-api
          version: terraform-intro-use

    - name: pip requirement.txt
      pip:
        requirements: /home/mymoji/mymoji-api/requirements.txt

    - name: nginx
      include_role:
        name: nginx

    - name: gunicorn
      include_role:
        name: gunicorn

    - name: supervisor
      include_role:
        name: supervisor

  #   - name: logging
  #     include_role:
  #       name: logging

  #   - name: monitoring
  #     include_role:
  #       name: monitoring

  # roles:
  #   - geerlingguy.clamav