---
- hosts: web
  gather_facts: no
  
  tasks:
    - name: common
      include_role:
        name: common

    - name: nginx
      include_role:
        name: nginx

    - name: gunicorn
      include_role:
        name: gunicorn

    - name: supervisord
      incloud_role:
        name: supervisord