---
- hosts: gcp
  gather_facts: no
  
  tasks:
    - name: common
      include_role:
        name: common

    - name: nginx
      include_role:
        name: nginx

    - name: gunicorn
      include_role:
        name: gunicorn

    - name: supervisor
      include_role:
        name: supervisor