---
# tasks file for roles/gcp-instance

- name: create a disk
  gcp_compute_disk:
    name: "{{ item.1.disk.name }}"
    size_gb: "{{ item.1.disk.size }}"
    source_image: "{{ item.1.disk.image }}"
    zone: "{{ item.0.zone }}"
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present
  with_subelements: 
  - "{{ nodes }}"    
  - boot_disk
  register: bootdisk


- name: create a address
  gcp_compute_address:
    name: "{{ item.1.nic.name }}"
    region: "{{ general.region }}"
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present
    scopes: "{{ scopes }}"
  with_subelements: 
  - "{{ nodes }}"    
  - ips        
  register: address


- name: create a network
  gcp_compute_network:
    name: default
    auto_create_subnetworks: 'true'
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present
  register: network


- name: create a firewall
  register: result
  gcp_compute_firewall:
    name: fw
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
    target_tags:
    - http-server
    - https-server
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present  


- name: create a instance
  gcp_compute_instance:
    name: "{{ item.name }}"
    machine_type: "{{ item.machine_type }}"

    deletion_protection: false
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ bootdisk.results.0 }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address.results.0 }}"
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - http-server
      - https-server  
    zone: "{{ item.zone }}"
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present
  with_items: 
  - "{{ nodes }}"        
  register: instance 


- name: create sql connection
  gcp_sql_instance:
    name: central-academy-292509:asia-east1:test
    settings:
      ip_configuration:
        authorized_networks:
        - name: "{{ item.name }}"
          value: "{{ address.results.0 |string }}"
      tier: db-n1-standard-1
    region: "{{ general.region }}"
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present 
  with_items: 
  - "{{ nodes }}"          