---
# tasks file for roles/gcp-instance

- name: create a disk
  gcp_compute_disk:
    name: "{{ item.1.disk.name }}"
    size_gb: "{{ item.1.disk.size }}"
    source_image: "{{ item.1.disk.image }}"
    zone: "{{ item.0.zone }}"

    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present
  with_subelements: 
  - "{{ nodes }}"    
  - boot_disk
  register: disk

# - name: create a network
#   gcp_compute_network:
#     name: network-instance
#     project: "{{ general.project }}"
#     auth_kind: "{{ general.auth_kind }}"
#     service_account_file: "{{ general.service_account_file }}"
#     state: present
#   register: network

- name: create a address
  gcp_compute_address:
    name: address-instance
    region: "{{ general.region }}"
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present
    scopes: "{{ scopes }}"
  with_subelements: 
  - "{{ nodes }}"    
  - ips        
  register: address

- name: create a instance
  gcp_compute_instance:
    name: "{{ instance.name }}"
    machine_type: "{{ instance.machine_type }}"

    deletion_protection: false
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ bootdisk.results.0 }}"
    zone: "{{ general.zone }}"
    project: "{{ general.project }}"
    auth_kind: "{{ general.auth_kind }}"
    service_account_file: "{{ general.service_account_file }}"
    state: present