---
# defaults file for roles/supervisor

supervisor_unix_http_server_socket_path: /var/run/supervisor/supervisor.sock
logfile: /var/log/supervisor/supervisord.log
logfile_maxbytes: 50MB
logfile_backups: 10
loglevel: info
pidfile: /var/run/supervisord.pid
nodaemon: false
minfds: 1024
minprocs: 200


supervisor.rpcinterface_factory: supervisor.rpcinterface:make_main_rpcinterface
serverurl: unix:///var/run/supervisor/supervisor.sock 

files: /etc/supervisord.d/*.conf