---
# tasks file for roles/monitoring
- name: Download monitoring agent reop shell
  get_url:
    url: https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
    dest: /home/mymoji/add-monitoring-agent-repo.sh

- name: Run shell
  command: bash /home/mymoji/add-monitoring-agent-repo.sh
  changed_when: false

- name: Install stackdriver-agent
  yum:
    name: stackdriver-agent
    state: present

- name: Restart stackdriver-agent service
  service:
    name: stackdriver-agent
    state: restarted