---
# tasks file for roles/supervisor
- name: install supervisor
  become: yes
  yum:
    name:
    - epel-release
    - supervisor

- name: update supervisor config
  become: yes
  copy:
    src: files/supervisord.conf
    dest: /etc/supervisord.conf

- name: add new config
  become: yes
  copy:
    src: files/app.conf
    dest: /etc/supervisord.d/app.conf

- name: service supervisor start
  become: yes
  service: 
    name: supervisord
    enabled: yes 
    state: started

- name: restart supervisor
  become: yes
  supervisorctl:
    name: app
    state: restarted

