---
# tasks file for roles/supervisor

- name: install epel-release
  dnf:
    name: epel-release
    state: latest

- name: install supervisor
  dnf:
    name: supervisor
    state: present

- name: update supervisor config
  copy:
    src: files/supervisord.conf
    dest: /etc/supervisord.conf

- name: add new config
  copy:
    src: files/app.conf
    dest: /etc/supervisord.d/app.conf

- name: start service supervisor
  systemd:
    name: supervisord.service
    enabled: yes
    state: started



