---
# tasks file for roles/supervisor
- become: yes

- name: install epel-release
  dnf:
    name: epel-release
    state: latest

- name: install supervisor
  yum:
    name: supervisor
    state: present

- name: update supervisor config
  copy:
    src: files/supervisord.conf
    dest: /etc/supervisord.conf

- name: add new config
  copy:
    src: files/app.conf
    dest: /etc/supervisord.d/app.conf

- name: start service supervisor
  service:
    name: supervisord
    enabled: yes

- name: supervisor start
  supervisorctl: 
    name: supervisord
    state: started
    config: /etc/supervisord.conf


