---
# tasks file for roles/supervisor
- name: install supervisor
  become: yes
  yum:
    name:
    - epel-release
    - supervisor

- name: service supervisor start
  become: yes
  service: 
    name: supervisord
    enabled: yes 
    state: started