---
# tasks file for roles/logging
- name: Download monitoring agent reop shell
  get_url:
    url: https://dl.google.com/cloudagents/add-logging-agent-repo.sh
    dest: /home/mymoji/add-logging-agent-repo.sh

- name: Run shell
  command: bash add-logging-agent-repo.sh
  changed_when: false

- name: Install google-fluentd
  yum:
    name: google-fluentd
    state: present

- name: Install google-fluentd-catch-all-config-structured
  yum:
    name: google-fluentd-catch-all-config-structured
    state: present

- name: Restart google-fluentd service
  service:
    name: google-fluentd
    state: restarted
