---
# tasks file for roles/common
- name: install package.
  become: yes
  yum:
    name: "{{ packages }}"
    state: present

  vars:
    packages:
    - '*'
    - git
    # - python3
    # - python3-devel
    # - python3-pip
    # - python-setuptools

- name: install flask
  become: yes
  pip:
    name: flask
    state: present

- name: install semanage
  become: yes
  pip:
    name: semanage
    state: present